FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY . .
COPY proxychains.conf /etc/proxychains.conf

RUN apk add proxychains-ng

RUN npm install

EXPOSE 3040

CMD export HOSTNAME="127.0.0.1"; \
    conf=/etc/proxychains.conf; \
    cat /etc/proxychains.conf; \
    proxychains -f $conf node app.js;
